# Generated by Django 4.2.2 on 2026-06-11 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_imobilizado', models.IntegerField(unique=True, verbose_name='Nº Imobilizado')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Nº de Série')),
                ('tipo', models.CharField(choices=[('DESKTOP', 'Desktop'), ('NOTEBOOK', 'Notebook'), ('MONITOR', 'Monitor'), ('IMPRESSORA', 'Impressora'), ('SCANNER', 'Scanner'), ('NOBREAK', 'Nobreak'), ('SWITCH', 'Switch'), ('ROTEADOR', 'Roteador'), ('TELEFONE_IP', 'Telefone IP'), ('PROJETOR', 'Projetor'), ('TABLET', 'Tablet'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('local', models.CharField(max_length=150, verbose_name='Local')),
                ('setor', models.CharField(max_length=150, verbose_name='Setor')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('EM_MANUTENCAO', 'Em Manutenção'), ('EMPRESTADO', 'Emprestado'), ('ESTOQUE', 'Estoque'), ('DESCARTADO', 'Descartado')], default='ATIVO', max_length=30, verbose_name='Status')),
                ('sistema_operacional', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operacional')),
                ('versao_so', models.CharField(blank=True, max_length=50, verbose_name='Versão do SO')),
                ('mac_ethernet', models.CharField(blank=True, max_length=17, verbose_name='MAC Ethernet')),
                ('mac_wifi', models.CharField(blank=True, max_length=17, verbose_name='MAC Wi-Fi')),
                ('versao_office', models.CharField(blank=True, max_length=100, verbose_name='Versão do Office')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Aquisição')),
                ('garantia_ate', models.DateField(blank=True, null=True, verbose_name='Garantia até')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('MEMORIA', 'Memória'), ('HD_SSD', 'HD / SSD'), ('FONTE', 'Fonte'), ('TECLADO', 'Teclado'), ('MOUSE', 'Mouse'), ('CABO', 'Cabo'), ('TONER', 'Toner'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Categoria')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('quantidade_minima', models.IntegerField(default=1, verbose_name='Quantidade Mínima')),
                ('unidade', models.CharField(default='unidade', max_length=20, verbose_name='Unidade')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='Localização')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=30, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipamento', verbose_name='Equipamento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='core.itemestoque', verbose_name='Item')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('tipo', models.CharField(choices=[('CORRETIVA', 'Corretiva'), ('PREVENTIVA', 'Preventiva'), ('UPGRADE', 'Upgrade')], max_length=30, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], default='ABERTA', max_length=30, verbose_name='Status')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='core.equipamento', verbose_name='Equipamento')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
