# Generated by Django 5.2.15 on 2026-06-11 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('segmento', models.CharField(choices=[('IVECO', 'IVECO'), ('AGROP.', 'Agrop.'), ('ROD.', 'Rod.'), ('V. VALE', 'V. Vale'), ('SEGUROS', 'Seguros'), ('CASE', 'Case'), ('FIAT', 'Fiat'), ('LOCADORA', 'Locadora'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Segmento')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
                'unique_together': {('nome', 'segmento')},
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='core.empresa', verbose_name='Empresa'),
        ),
    ]
