# Generated by Django 5.2.15 on 2026-06-11 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_equipamento_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='empresa_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='core.empresa', verbose_name='Empresa Destino'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='empresa_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='core.empresa', verbose_name='Empresa Origem'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste')], max_length=30, verbose_name='Tipo'),
        ),
    ]
