# Generated by Django 5.2.15 on 2026-06-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movimentacaoestoque_empresa_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Computador')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('usuario', models.CharField(blank=True, max_length=200, verbose_name='Último Usuário')),
                ('fabricante', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nº de Série')),
                ('processador', models.CharField(blank=True, max_length=200, verbose_name='Processador')),
                ('memoria_gb', models.IntegerField(blank=True, null=True, verbose_name='Memória (GB)')),
                ('sistema_operacional', models.CharField(blank=True, max_length=200, verbose_name='Sistema Operacional')),
                ('ultimo_logon', models.DateTimeField(blank=True, null=True, verbose_name='Último Logon')),
                ('status_rede', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('desconhecido', 'Desconhecido')], default='desconhecido', max_length=20, verbose_name='Status de Rede')),
                ('origem', models.CharField(default='inventario_automatico', max_length=50, verbose_name='Origem')),
                ('data_ultima_sincronizacao', models.DateTimeField(auto_now=True, verbose_name='Data da Última Sincronização')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Ativo de Rede',
                'verbose_name_plural': 'Ativos de Rede',
                'ordering': ['nome'],
            },
        ),
    ]
