# Generated by Django 5.2.15 on 2026-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='numero_imobilizado',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nº Imobilizado'),
        ),
    ]
