# Generated by Django 5.2.15 on 2026-06-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_equipamento_numero_imobilizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('OFFLINE', 'Offline'), ('EM_MANUTENCAO', 'Em Manutenção'), ('EMPRESTADO', 'Emprestado'), ('ESTOQUE', 'Estoque'), ('DESCARTADO', 'Descartado')], default='ATIVO', max_length=30, verbose_name='Status'),
        ),
    ]
