# Generated by Django 5.2.15 on 2026-06-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_equipamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='teamviewer_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='TeamViewer ID'),
        ),
    ]
