# Generated by Django 5.2.15 on 2026-06-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_equipamento_teamviewer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
    ]
