# Generated by Django 5.2.15 on 2026-06-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipamento_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ativo',
        ),
    ]
