# Generated by Django 5.2.15 on 2026-06-18 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(max_length=100, verbose_name='Tabela')),
                ('registro_id', models.IntegerField(verbose_name='ID do Registro')),
                ('campo', models.CharField(max_length=100, verbose_name='Campo')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, verbose_name='Valor Novo')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Alteração',
                'verbose_name_plural': 'Logs de Alterações',
                'ordering': ['-data'],
            },
        ),
    ]
