# Generated by Django 5.2.15 on 2026-06-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_logalteracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTOQUE_BAIXO', 'Estoque Baixo'), ('GARANTIA_PROXIMA', 'Garantia Próxima do Vencimento'), ('MANUTENCAO_ATRASADA', 'Manutenção Atrasada'), ('INFO', 'Informativo')], max_length=30, verbose_name='Tipo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Link')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
