# Generated by Django 5.2.15 on 2026-06-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='periodicidade_dias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Periodicidade (dias)'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='proxima_manutencao',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Manutenção'),
        ),
    ]
