# Generated by Django 5.2.15 on 2026-06-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_equipamento_periodicidade_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='ultimo_usuario',
            field=models.CharField(blank=True, max_length=200, verbose_name='Último Usuário'),
        ),
    ]
