# Generated by Django 5.2.15 on 2026-06-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_equipamento_ultimo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='responsavel',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Responsável'),
        ),
    ]
