# Generated by Django 5.2.15 on 2026-06-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_equipamento_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf', models.CharField(max_length=50, unique=True, verbose_name='Nº Nota Fiscal')),
                ('serie', models.CharField(blank=True, max_length=20, verbose_name='Série')),
                ('fornecedor_nome', models.CharField(max_length=255, verbose_name='Fornecedor')),
                ('fornecedor_cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('data_compra', models.DateField(verbose_name='Data da Compra')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('arquivo_nf', models.FileField(blank=True, null=True, upload_to='compras/nf/', verbose_name='Arquivo NF (PDF/XML)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Nº de Série')),
                ('patrimonio', models.CharField(blank=True, max_length=100, verbose_name='Nº Patrimônio')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('meses_garantia', models.IntegerField(default=0, verbose_name='Garantia (meses)')),
                ('meses_vida_util', models.IntegerField(default=0, verbose_name='Vida Útil (meses)')),
                ('data_fim_garantia', models.DateField(blank=True, null=True, verbose_name='Fim da Garantia')),
                ('data_fim_depreciacao', models.DateField(blank=True, null=True, verbose_name='Fim da Depreciação')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.compra', verbose_name='Compra')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_compra', to='core.equipamento', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Item da Compra',
                'verbose_name_plural': 'Itens da Compra',
            },
        ),
    ]
